### ISSUE TITLE
Gutter indicators

### ISSUE THREAD

**Issue by hoffmael** [mrcrowl/vscode-hg#1]
Great to see mercurial integrated to VS code! To match git functionality I'd love to be able to see local changes indicated per line in the gutter: https://code.visualstudio.com/docs/editor/versioncontrol#_gutter-indicators

![image](https://cloud.githubusercontent.com/assets/24258055/25346644/60ba79a2-28d5-11e7-861f-4b8262dbb10e.png)

**Comment by mrcrowl** [comment]
@hoffmael Hmm... there must be some configuration setting that I haven't taken into account.  The gutters are definitely intended to work like git.

On my machine (Windows 8.1, VS Code 1.11.2, Mercurial 4.1.2) the gutters look like this:
![gutters](https://cloud.githubusercontent.com/assets/1796256/25358880/203b91d2-2997-11e7-99b2-4b8eab58d2df.gif)

Can you please send me your OS, VS code and hg version?

Also, please check that the version of hg that the extension is using is the one you expect. Output > Hg > (scroll to top) to see something like:
![image](https://cloud.githubusercontent.com/assets/1796256/25359016/a4ca9182-2997-11e7-9bb3-6b5273521018.png)

Lastly, can you please run this command in the terminal window:
`hg cat Program.cs -r .`

That should output the contents of Program.cs at the last revision.

**Comment by hoffmael** [comment]
Ah, you are right, if I restart VS code I see the gutters working as expected. I think the issue comes from a hang while refreshing the repo state. I the progress bar spinning waiting on something, I'm suspecting the hg incoming command timed out due to a slow server and hung the hg summary command.

![image](https://cloud.githubusercontent.com/assets/24258055/25361262/7a12c294-290a-11e7-9858-1c63445c86cc.png)

**Comment by mrcrowl** [comment]
Ah, yes, it does look like a hang.  `hg incoming` is called by the auto-incoming/outgoing counter.

A couple of settings (.vscode\settings.json or user settings) that may help in the meantime, until I can resolve the hang:
```
"hg.autoInOut": false,  // disable the auto-incoming/outgoing counter
"hg.commandMode": "cmdline" // uses command line instead of cmdserve
```

Also, could you run `hg incoming -q` from the terminal and let me know if there are any unexpected messages / prompts appearing that might be causing the hang?  Possibly authentication?

**Comment by mrcrowl** [comment]
Also, please try `hg outgoing -q` from the terminal.  It might be the next command that's hanging.

**Comment by hoffmael** [comment]
This looks to be resolved by just setting "hg.commandMode": "cli". Repo refresh and side-by-side diffs no longer hang. I was able to keep hg.autoInOut as true with command line mode.

**Comment by hoffmael** [comment]
After a little more testing this seems to be working well. Thank you for the quick response. CLI might need to become the default command mode.

This can be closed.
