### ISSUE TITLE
Release 1.6.0

### ISSUE THREAD

**Issue by incidentist** [mrcrowl/vscode-hg#108]
I made a milestone for 1.6.0 to keep track of what's new for that version. I think it's ready to go. @mrcrowl Can you cut the release?

**Comment by mrcrowl** [comment]
Writing up the changelog notes now. 

Issue #18: the shelve commands only work if you have the extension installed. If it's uninstalled the hg log shows `hg: unknown command 'shelve'`, and the UI silently swallows that error. Not sure this is what we want.

**Comment by mrcrowl** [comment]
I've put a notice about the extension being required in the readme, and raised a new issue for it #109

**Comment by mrcrowl** [comment]
v1.6.0 release! 🎉   .... thanks gents.
