### ISSUE TITLE
Automatically enable extensions when their commands are run

### ISSUE THREAD

**Issue by mrcrowl** [mrcrowl/vscode-hg#109]
Related to Issue #18 and PR #96:

PR #96 introduced the various shelve commands: Shelve/Unshelve/etc. However, these commands require that the hg shelve extension is enabled, i.e.
```
[extensions]
shelve=
```
... must be present in `.hgrc` or repo's `hgrc` file.

Without this, the commands silently fail. The hg log window shows:
```
hg: unknown command 'shelve'
(did you mean one of resolve, serve?)
```

The UI should detect this error message and provide a link to instructions on how to enable shelving.

**Comment by incidentist** [comment]
Ah, good catch. There's actually a way to enable extensions via command line at runtime. If that works we wouldn't need a message.

**Comment by hdpoliveira** [comment]
With https://github.com/mrcrowl/vscode-hg/pull/104 I introduce some error handling for missing extensions.
Not perfect, but at least it doesn't fail silently

**Comment by incidentist** [comment]
@mrcrowl What version of hg did you use to get that error message? I'm on hg 5.4.0 and even when I remove shelve from my extensions list in .hgrc, and verify that `shelve` doesn't appear when I run `hg config`, I can still run shelve/unshelve, even in a new repo. If I remove `purge` from extensions and try a purge, I *do* see the `unknown command` message.

**Comment by incidentist** [comment]
Ah, shelve is always on by default starting in hg 5.1.
