### ISSUE TITLE
Support file renames

### ISSUE THREAD

**Issue by ghost** [mrcrowl/vscode-hg#139]
At the moment there does not seem to be any way to rename files from within VSCode such that Mercurial would keep track of the rename. Doing it from the command line of course works, but then one has to go through the slightly cumbersome step of closing and reopening the file in VSCode.

1. Would it be possible for the extension to hook into the VSCode explorer rename feature to tell Mercurial of the rename?
2. If VSCode doesn't make this easy, would it be possible to provide the rename functionality in the SCM tab?

**Comment by hdpoliveira** [comment]
No1 may be feasible by listening to the onDidRenameFiles workspace event.

**Comment by Alphare** [comment]
Just so it's said: `hg move source target --after` (or the same with `copy`) would work if run in the right hook from VSCode.

**Comment by incidentist** [comment]
This will ship in 1.8.0.
