### ISSUE TITLE
Conflict with blackbox extension

### ISSUE THREAD

**Issue by ajansveld** [mrcrowl/vscode-hg#14]
Turning on the Mercurial [blackbox](https://www.mercurial-scm.org/wiki/BlackboxExtension) logging extension causes vscode to run its hg status* commands in a tight loop, noticeable by the flashing blue badge on the Source Control icon in the Activity Bar.

The extension writes its log files in the repo's .hg folder, perhaps that triggers this behavior?

\*
hg status -C
hg cat \<filename\> *(multiple times)*
hg summary -q
hg bookmarks

**Comment by ajansveld** [comment]
This doesn't seem to be resolved completely, there are still multiple `hg cat` calls when the blackbox extension is enabled. Not sure if you saw my comment [here](https://github.com/mrcrowl/vscode-hg/commit/48aef4e53e2482102f015b5e4581b20942a0474c).

**Comment by mrcrowl** [comment]
@ajansveld can you provide me with a small repro?  I've tried enabling blackbox and can't see the behaviour you're describing.

**Comment by ajansveld** [comment]
Sure:
- Enable the blackbox extension through the TortoiseHg UI or by setting this in your .hgrc or Mercurial.ini:
```
[extensions]
blackbox = 
```

- Open vscode in a local clone, e.g. `code C:\temp\test\sandbox\local\`
- Open a file in that repo, e.g. abd.txt
- Run the `Hg: Show hg output` command from the Command Palette
- See the "hg cat abcd.txt" commands scroll by

Closing the file tab will stop the hg cat commands.

Hope this helps,
Arnoud

**Comment by ajansveld** [comment]
I think this is caused by the blackbox extension creation log files with multiple extensions, e.g.
```
.hg\.blackbox.log-ji0kbu
.hg\.blackbox.log-ji7eat
.hg\.blackbox.log-msyu4j
.hg\.blackbox.log-wbymm5
.hg\blackbox.log
```

Suggestion for a fix: change (in [src/model.ts](https://github.com/mrcrowl/vscode-hg/blob/master/src/model.ts))
```
const isRelevant = !/[\\\/]\.hg[\\\/](\w?lock.*|.*\.log)$/.test(uri.fsPath);
```
to:
```
const isRelevant = !/[\\\/]\.hg[\\\/](\w?lock.*|.*\.log(-\w+)?)$/.test(uri.fsPath);
```
Thanks!

**Comment by mrcrowl** [comment]
@ajansveld Thanks for investigating further.  Could you try installing [this version](https://github.com/mrcrowl/vscode-hg/releases/tag/1.1.5) manually?

**Comment by ajansveld** [comment]
Bummer, 1.1.5 still exhibits the issue. Procmon shows that the blackbox extension writes two more temporary files to .hg (sorry, should have checked this before):
```
.hg\blackbox.log.hgtmp1
.hg\blackbox.log.hgtmp2
```
These are not excluded by the suggested code, can you change it to `const isRelevant = !/[\\\/]\.hg[\\\/](\w?lock.*|.*\.log([-\.]\w+)?)$/.test(uri.fsPath);`?

**Comment by mrcrowl** [comment]
Bugger! Try [this one instead](https://github.com/mrcrowl/vscode-hg/releases/tag/v1.1.6).

**Comment by ajansveld** [comment]
Winner! Thanks!
