### ISSUE TITLE
No changes list after commit

### ISSUE THREAD

**Issue by jhony1104** [mrcrowl/vscode-hg#150]
After a commit, it can happen that the changes list is no longer visible/no longer exists. The only way to restore it is to restart/reload vscode.

Other functions like rollback still work.

Trying to switch between list and tree view (in error state) results in: `Cannot read property 'templateData' of null`

vscode-hg: 1.6.0

Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-14T00:13:57.513Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.0-9-amd64

**Comment by hdpoliveira** [comment]
@jhony1104 could you please watch out for this?

If/when it happens, please send us a print of the screen and the log of the extension (accessible via >Show hg output in the command palette) if possible.

**Comment by jhony1104** [comment]
Since I stopt seeing the issue and therefore can no longer reproduce it, I closed the issue.

**Comment by hdpoliveira** [comment]
Thanks @jhony1104 !
