### ISSUE TITLE
Gutter diff on left margin not working

### ISSUE THREAD

**Issue by shriniwas26** [mrcrowl/vscode-hg#160]
VS Code version: 1.48.0
Extension version: 1.7.0

The diff is available when viewing it explicitly:
![image](https://user-images.githubusercontent.com/3761636/90530700-7a72f980-e175-11ea-8cb0-f044bec68deb.png)

Gutter diff is not visible: 
![image](https://user-images.githubusercontent.com/3761636/90530762-8c549c80-e175-11ea-9aed-a82e6ae30ed6.png)

**Comment by hdpoliveira** [comment]
Hi @shriniwas26 ! Thanks for reporting this!
This is an issue in vscode itself: https://github.com/mrcrowl/vscode-hg/issues/158
We have coded a change that works around the issue and will release soon.
