### ISSUE TITLE
Serena Dimesions

### ISSUE THREAD

**Issue by Danieleeee** [mrcrowl/vscode-hg#17]
Hi, 
is possible to use your extensions with Serena Dimensions SCM?

**Comment by mrcrowl** [comment]
I don't think that's possible... *unless *Serena Dimensions CM happens to
be use mercurial under the hood?

You're most welcome to use the vscode.hg source as a basis for developing a
new SCM provider in vscode though, if that helps.

See
https://github.com/Microsoft/vscode-docs/blob/vnext/docs/extensionAPI/api-scm.md
