### ISSUE TITLE
Please release extension for OpenVSX

### ISSUE THREAD

**Issue by chintan-mishra** [mrcrowl/vscode-hg#170]
OpenVSX is the Eclipse Foundation powered marketplace for VSCode builds not affiliated to Microsoft. I have recently started using [VSCodium](https://vscodium.com/) which is a telemetry-free open source build for VSCode. It is unclear if using Microsoft VSCode Marketplace is entirely legal.

Thus, I request you to release your extension on https://open-vsx.org.

I volunteer to help you maintain this plugin on OpenVSX.

**Comment by mrcrowl** [comment]
Hey Chintan, yeah I’m familiar with OpenVSX through my work. Happy to put
it up there too.

**Comment by chintan-mishra** [comment]
Thank you @mrcrowl

**Comment by SamB** [comment]
@brianking responded in https://github.com/EclipseFdn/open-vsx.org/issues/496#issuecomment-841175734:

> Granted, looking forward to your contributions!

So I guess you're clear to upload now?

**Comment by SamB** [comment]
In the meantime, we can use the VSIX files from https://github.com/mrcrowl/vscode-hg/releases.

**Comment by mrcrowl** [comment]
Sorry for the absurd delay in getting this done. Hg is now published at https://open-vsx.org/extension/mrcrowl/hg

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/1796256/157862711-ab9abeda-ca03-4448-9937-367bf7bf99a7.png">
