### ISSUE TITLE
Support for shelve/unshelve

### ISSUE THREAD

**Issue by gep13** [mrcrowl/vscode-hg#18]
Have you thought about adding support for doing shelve/unshelve operations within this extension?

**Comment by mrcrowl** [comment]
Thanks for the suggestion.  Let me know your thoughts about how this would be best integrated.  I'm undecided on this at the moment.

**Comment by gep13** [comment]
@mrcrowl I was worried that you might ask that 😄 

Using an example of how SourceTree does it... You have the option of creating a shelve at any point.  You are prompted for a shelve name, and then all uncommitted changes are added to it and removed from uncommitted changes.  You then have the ability to view existing shelves, and choose to unshelve it.

I could see those options being additional commands in the Hg extension, similar to push, pull, etc.

What do you think?

**Comment by mrcrowl** [comment]
Thanks for the ideas.  I think I'll wait for some others to vote on this before investing too much time on it. 
I'm open to a pull-request if you're interested in having a crack at it.

**Comment by gep13** [comment]
@mrcrowl It is unlikely that I will be able to help with this, already juggling too many OSS projects as it is.  Sorry!

**Comment by chrsmrtn-** [comment]
My team just grabbed this extension and this was one of the things that came up that we'd love to have.

**Comment by opus-2** [comment]
As another example, TortoiseHg does a great job with shelves, a little more flexible than what @gep13 described (you can select which uncommited files will be shelved, not just "all").

**Comment by gep13** [comment]
@opus-2 sounds good to me 👍
