### ISSUE TITLE
Hg SCM Provider not displayed in Switch SCM Provider... choices

### ISSUE THREAD

**Issue by gregvanl** [mrcrowl/vscode-hg#19]
Install the HG extension and reload VS Code
In the Source Control view, go to the More... menu and select Switch SCM Provider...
There is no entry for Hg.
There is no indication that a dependency might be missing.

**Comment by mrcrowl** [comment]
Can you open the Output panel, and see if Hg is in the dropdown list?

If that is showing, do you see any messages in the Hg output?

**Comment by gregvanl** [comment]
Yes, Hg is in the Output dropdown and shows:
Could not find hg, tried:
 - C:\Program Files\Mercurial\hg.exe
 - C:\Program Files (x86)\Mercurial\hg.exe
 - C:\Program Files\TortoiseHg\hg.exe
 - C:\Program Files (x86)\TortoiseHg\hg.exe
 - hg
Indeed I don't have Mercurial installed so this might be "by design".

It would be less confusing if I could switch to the Hg provider and then be prompted to install Mercurial or any other dependency required. VS Code does that for the Git integration. If VS Code can't find git.exe, it presents a message and a pointer to gitscm.org.

You might also consider reordering the extension README, putting the Prerequisites first. The Getting Started section is pretty far down.
