### ISSUE TITLE
Great extension! Enhancement suggestion - open multiple files from context menu.

### ISSUE THREAD

**Issue by nioh-wiki** [mrcrowl/vscode-hg#2]
If you select multiple files from the list of tracked/untracked files (shift/ctrl + right click) and select "Open Changes" or "Open File" from the context menu, it only opens one file. Could you please make this open multiple files? Thanks!

Visual Studio Code 1.11.2 (Ubuntu)
Hg 1.0.2

**Comment by mrcrowl** [comment]
Thanks for letting me know. I'll look into this.

**Comment by mrcrowl** [comment]
@nioh-wiki these content menu options are now working as expected in Hg 1.0.3
