### ISSUE TITLE
Conflicts with git extension

### ISSUE THREAD

**Issue by jerivas** [mrcrowl/vscode-hg#24]
It seems like the Mercurial extension breaks the git SCM provider from marking changes in the gutter. I started noticing this with VSCode 1.16.0, when multiple SCM provider support was added. https://code.visualstudio.com/updates/v1_16#_source-control

- VSCode Version: 1.16.0
- OS Version: Windows 10

Steps to Reproduce:

1. Install the Mercurial extension.
2. Open a project that uses a git repo.
3. Edit some files. The git sidebar pane detects the changes, but they are not marked in the gutter.
4. Disable the Mercurial extension and the git gutter markers come back.

Reproduces without extensions: No

**Comment by mrcrowl** [comment]
Thanks @jerivas, and sorry for the trouble. Hg wasn't updated to compensate for multiple SCM providers, introduced in vscode 1.1.6.0. The context flag it relied on was `scmProvider = hg` which was deprecated.

Work is now underway to correct this in #29.
