### ISSUE TITLE
Correctly adopt multirepo SCM

### ISSUE THREAD

**Issue by devuxer** [mrcrowl/vscode-hg#26]
Since upgrading to VSCode 1.16.0, which supports multiple SCM providers, I'm having issues with the vscode-hg. extension. It attempts to track uncommitted files even for Git projects, which causes the SCM badge to show 99+ even though all my changes have been committed.

The VSCode developers claim this is definitely an issue with this extension and not VSCode (for reference, please see https://github.com/Microsoft/vscode/issues/34313).

**Comment by mrcrowl** [comment]
Thanks @devuxer. Work is underway to correct this. Please follow issue #29.
