### ISSUE TITLE
Extensions creates runaway Python process

### ISSUE THREAD

**Issue by joejo-unity** [mrcrowl/vscode-hg#28]
Using both VSCode 1.16 and 1.17, I have had issues with an errant subprocess of VSCode sucking up all RAM/DISK on my machine causing the OS to panic. After disabling extension after extension it appears that the culprit is this Hg extension. 

The first issue is that the process, as it runs, is eating up every resource it is able to get a hold of. The second issue is that, when VS Code is quit this child process is not being destroyed/torn down. So, even when I try to be proactive an make sure that VSCode doesn't kill me.... it still does because of this still running Python process.

**Comment by mrcrowl** [comment]
@joejo-unity, sorry for the slow response.

Does this happen in Hg repos?  Or only in repos using other source control providers?

**Comment by mrcrowl** [comment]
Also, please let me know if the v1.2.0 update makes any difference.
