### ISSUE TITLE
[Request] Hide untracked files

### ISSUE THREAD

**Issue by savioret** [mrcrowl/vscode-hg#3]
Hello, 

First, thanks for this module !
My project has thousands of untracked files, which slows down the status query.
 I use to perform a "hg status -q" or "hg status -mar" it would be nice if I could set this from the config, or just a flag to indicate the I don't want to show untracked files.

Thank you.

**Comment by mrcrowl** [comment]
Okay. Please forgive me for asking. But is this a situation where you can't
use a .hgignore file for some reason?

**Comment by savioret** [comment]
You are right, it solves the problem, and it is a valid solution for me.
Thanks, I proceed to close the issue.
