### ISSUE TITLE
Trouble resolving merge conflicts with Mercurial and vscode

### ISSUE THREAD

**Issue by erocheleau** [mrcrowl/vscode-hg#32]
I have done a simple `hg merge branch` into my current branch.

2 files are in merge conflicts. They are shown correctly separate from the other files that were auto-merged.
However when trying to open the conflict files to see the comparison about what changed I get the following error:

`Unable to open 'gulpfile.js (local <-> other)': Unexpected token p in JSON at position 0.`

Also when trying to resolve the file, I get this error:

`'echomsg' is not recognized as an internal or external command, operable program or batch file.`

in the hg output log.

Don't really know what other information I could provide?

**Comment by erocheleau** [comment]
Using hg 4.2.1
Vscode Version 1.17.2

**Comment by ghusse** [comment]
Same thing with mercurial 4.3.1, VSCode 1.19.2 on Linux

**Comment by P9GIT** [comment]
I have exactly the same problem on Linux Mint 17.2.

HG: 4.4.1
VSC: 1.22.2
HG extension mcrowl: 1.2.3

This makes it impossible for me to use VSC :(

**Comment by ghusse** [comment]
@P9GIT  As a workaround, you can right-click on the file and select "open files". 

Could it be possible to make it the default behavior?

**Comment by P9GIT** [comment]
Hi @ghusse 

Thanks for your suggestion. 
Unfortunately this does not help me resolve the merge conflict for the file as I still can't open the changes view without getting an exception.

**Comment by feakuru** [comment]
any progress on this? how can I help? maybe provide some logs?

**Comment by dnistreanu** [comment]
I can confirm this issue is still reproducible:
HG - v1.3.0
VsCode - 1.43.2
OS - Windows x10 Pro

**Comment by mrcrowl** [comment]
Released in [v1.5.1](https://github.com/mrcrowl/vscode-hg/releases/tag/v1.5.1). Thanks @incidentist!
