### ISSUE TITLE
Add color argument when invoking hg [Was: Mercurial update breaks the plugin]

### ISSUE THREAD

**Issue by adab4d** [mrcrowl/vscode-hg#39]
On an Ubuntu 16.04 using Visual Studio Code 1.19.2 and Hg extension v1.2.2-3, updating the system's mercurial from 3.7.3 to 4.4.1 using [official PPA](https://launchpad.net/~mercurial-ppa/+archive/ubuntu/releases) results in an empty Source Control area in side bar.

There are no modified or untracked files, the source control is recognized as "HG".

Using mercurial in command line works without flaws.

Reverting to previous version fixes the issue.

**Comment by adab4d** [comment]
This is not sistematic, sometimes I get a working vscode Source Control side bar with 4.4.

I'm not sure where I can gather relevant info from the plugin, any hint about that appreciated.

**Comment by adab4d** [comment]
I stand corrected, it turned out I had already updated my global hgrc to use builtin color extension rather and the `color = always` is what actually messes up vscode-hg.

Turns out when reverting to 3.7.3 the ui.color setting was not effective and therefore the vscode-hg worked just fine.

The issue is then actually a feature request, please either force `--color=never` when calling mercurial or provide a setting to inject arguments when invoking mercurial so each user can pick his own poison.

**Comment by adab4d** [comment]
In case someone else hits the same issue, just create an `hg-no-color` wrapper containing:

    #!/bin/sh
    
    /usr/bin/hg --config ui.color=never "$@"

**Comment by incidentist** [comment]
Fixed in 1.4.0. The extension now ensures color output is disabled when running its commands.
