### ISSUE TITLE
Can't commit message containing non-ascii chars

### ISSUE THREAD

**Issue by dpetukhov** [mrcrowl/vscode-hg#4]
Hi.

Thanks for great plugin - it's very easy for use.
When I try to commit with message like 'Поправил загрузку Roboto в стилях' - plugin can't do it.

Here is the log:

> hg commit style.css -m Поправил загрузку Roboto в стилях
> transaction abort!
> rollback completed
> abort: decoding near 'Попра': 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)!

**Comment by mrcrowl** [comment]
Thanks Dmitry. I'll see if I can sort that out for you.

**Comment by mrcrowl** [comment]
@dpetukhov mac/windows/linux version?

**Comment by mrcrowl** [comment]
Here's the [previous version](https://www.dropbox.com/s/2xkig0et5vgw82b/easy-less-1.4.1.vsix?dl=0) as a .vsix file.

You can install via Extensions > Triple dot menu > Install from vsix

**Comment by mrcrowl** [comment]
Please ignore last message, wrong issue :face_with_head_bandage:

**Comment by dpetukhov** [comment]
I have issues with linux version, I'm using Ubuntu 16.04.
Just tested on windows - it's working correct there.

**Comment by mrcrowl** [comment]
@dpetukhov can you please check if you have an HGENCODING environment variable on windows?

From cmd prompt: `SET`, and check if HGENCODING is in the list.

That _might_ be the difference?

**Comment by mrcrowl** [comment]
@dpetukhov Hg v1.0.4 has been published, and hopefully helps resolve the issue with unicode commit messages.

**Comment by dpetukhov** [comment]
Thanks, I will check it in few days and let you know.

**Comment by dpetukhov** [comment]
And I have not set hgencoding on windows.

**Comment by dpetukhov** [comment]
I have checked new release and everything works fine now. Thanks!
