### ISSUE TITLE
Temporary / SCM files are passed to the linter

### ISSUE THREAD

**Issue by nbastin** [mrcrowl/vscode-hg#40]
For some reason files that don't exist are being passed to the linter, which causes a mess of spurious errors to show up in the problems tab.

For example if I have a file `/repos/inv-serve/bin/invsrv`, I will then get a linter file called 'invsrv.hg' that is located at `hg-original:/repos/inv-serve/bin/invsrv.hg?%7B%22path%22%3A%22%2Frepos%2Finv-serve%2Fbin%2Finvsrv%22%3A%22%22%7D`, and of course the linter spectacularly fails on this file and produces tons of problems.

**Comment by hdpoliveira** [comment]
I believe this was fixed by @incidentist with https://github.com/mrcrowl/vscode-hg/commit/590bc247c7daf4a36e4413c0a67602597451441a

**Comment by incidentist** [comment]
I think so too. Closing for now.
