### ISSUE TITLE
How to implement precommit hook?

### ISSUE THREAD

**Issue by PerfectionCSGO** [mrcrowl/vscode-hg#43]
I'm trying to figure how to implement a precommit hook for vscode but I've found it quite difficult to grasp.  There seem to be simple to use libraries for .git based projects but for .hg it's kind of a mess or always abandoned/out of date.

**Comment by mrcrowl** [comment]
Your issue sounds like it is with hg itself, not this extension. I have used hooks with hg + this extension before. It requires python from memory (because hg itself is python-based). 

See https://www.mercurial-scm.org/wiki/HookExamples
