### ISSUE TITLE
Feature request: annotate lines in a file

### ISSUE THREAD

**Issue by KristjanTammekivi** [mrcrowl/vscode-hg#45]
Would be really handy to see who changed a line and when / what revision. Could be done similarly to GitLens, where the blame is shown in a faded out color at the end of the current line (https://github.com/eamodio/vscode-gitlens)

**Comment by KristjanTammekivi** [comment]
I implemented it but as MrCrowl is inactive right now I temporarily published it under [KristjanTammekivi.hg](https://marketplace.visualstudio.com/items?itemName=KristjanTammekivi.hg) in case anyone is interested in this feature.

**Comment by mrcrowl** [comment]
Hey @KristjanTammekivi ... thanks for taking on the annotate development for vscode-hg.  As you've rightly detected, I'm a bit out of action at the moment for this project.

My workplace is switching to git, so there is less of an incentive for me to continue maintaining the hg extension.  

If you would like to take over its development, I would be happy to hand over access to the repo + extension (if that's possible?)

**Comment by KristjanTammekivi** [comment]
Hi, I'm expecting a similar development at my work so I don't have motivation to maintain it either. I might take a look at a couple of bugs while we haven't migrated yet though
