### ISSUE TITLE
How to install for Visual Studio Community 2017

### ISSUE THREAD

**Issue by matteshe** [mrcrowl/vscode-hg#47]
Hi,

if I try to install the addin it show following error message from install process:

15.05.2018 10:35:40 - Installiertes Produkt gefunden - Visual Studio Community 2017
15.05.2018 10:35:40 - VSIXInstaller.NoApplicableSKUsException: Diese Erweiterung kann auf den derzeit installierten Produkten nicht installiert werden.
   bei VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   bei VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()

**Comment by mrcrowl** [comment]
Sorry, this is an extension for Visual Studio Code only.  It is not supported by Visual Studio Community.
