### ISSUE TITLE
Multiline message commit

### ISSUE THREAD

**Issue by MattiaVicari** [mrcrowl/vscode-hg#52]
Hi all,
I think it is a good thing make the possible to write a multiline message for commit.
I see that the message is in one line (the ENTER command is used for confirm the commit).
However, a workaround is also welcome!

Thank you

![image](https://user-images.githubusercontent.com/29706978/42434990-764ea10e-8355-11e8-8112-9677dd3a8676.png)

**Comment by mrcrowl** [comment]
Sorry @MattiaVicari ... I believe this limitation comes from vscode itself.
