### ISSUE TITLE
Support VCS operations using drag-n-drop.

### ISSUE THREAD

**Issue by DmitrySokolov** [mrcrowl/vscode-hg#53]
For instance, when I move a file in VS Code's Explorer sidebar (using mouse) this file is not processed as `hg rename ...`.

**Comment by mrcrowl** [comment]
Won't be supporting this sorry, which sucks, because hg is pedantic about renames. I'm limited by what's available in vscode extension api, and I don't intend to monitor the disk for renames. The other alternative of introducing hg specific renames / moves feels gross too.
