### ISSUE TITLE
"discard" fails with an error when "log" has an alias set

### ISSUE THREAD

**Issue by jwendel** [mrcrowl/vscode-hg#55]
I have a change that shows up in the Source Control view.  When I click "Discard changes", I get an error of:
    Cannot read property 'split' of undefined
The last line that shows up in the HG output log is:
    hg log -T {rev}:{node}:{date|hgdate}:{author|person}:{branch}:{join(bookmarks,'\t')}:{sub('[\n\r]+',' ',desc)}\n -r parents()

VSCode: 1.25.1
HG plugin: 1.2.3
Windows 10 pro
Mercurial Distributed SCM (version 4.6.1)

Cause:
In my mercurial.ini (hgrc), I had this in my [ui] section:
   log = log -G

Commenting this out fixed the issue.

**Comment by veswill3** [comment]
I have this issue as well, and thanks @jwendel for helping me figure out how to fix it

**Comment by mrcrowl** [comment]
Interesting problem. Are you satisfied with your workaround? 

Log unfortunately could be aliased to anything, so not sure how to avoid unpredictable output. 

As far as I'm aware hg doesn't have low-level "porcelain" commands like git, and I don't think it's reasonable to mess with a user's hgrc/.ini files. 

Suggestions?

**Comment by veswill3** [comment]
Meh. hg defaults have been deprecated for reasons similar to this.
We should probably just setup an alias to do what we need and leave `log` along. something like this.

```
[alias]
lg = log -G
```
