### ISSUE TITLE
Password not asked when push

### ISSUE THREAD

**Issue by JaderCM** [mrcrowl/vscode-hg#59]
When click to push the changes, no password is prompted. So, the process to push the changes is in infinite loop.
![hg-vsc](https://user-images.githubusercontent.com/33452163/46244839-faa2e100-c3dc-11e8-8734-3f0e61ee41ab.gif)

**Comment by taivasverkko** [comment]
Same here. I managed to come up with a workaround by adding following section to hgrc file inside .hg directory :
```
[auth]
bb.prefix = https://bitbucket.org/
bb.username = mg
bb.password = something
```

https://stackoverflow.com/questions/2297942/hg-push-with-credentials-for-http-server

**Comment by eazrael** [comment]
Workaround for what? saving your password in plaintext to disk? Setting 
```
[paths]
default = https://user:password@host/path
```
works, too. 

My workaround: 

1. Open integrated terminal
2. type hg push, press enter
3. Enter password

**Comment by JaderCM** [comment]
@eazrael this workaround means: "I'm not using the plugin." :smiley:

**Comment by incidentist** [comment]
Looking into this more, the problem I was able to reproduce is that connecting to a remote that uses http auth displays an error message saying `Hg: http authorization required for <repo url>`. There's not a whole lot we can do to handle http auth properly right now. I suggest one of the following:

1. Use SSH auth with public key authentication.
2. Use the [`mercurial-keyring`](https://pypi.org/project/mercurial_keyring/) extension. Once it's installed and enabled in your .hgrc, run `hg outgoing` from a terminal in your repo root and enter your password for it to save. You can verify that it saved correctly by running `hg outgoing` again.

Our short term fix will probably be a popup suggesting one of these methods.

**Comment by hdpoliveira** [comment]
@incidentist the original issue reports a never ending push, which probably means the push command is stuck waiting for a password input. Were you able to see this behavior?

**Comment by incidentist** [comment]
No, I didn't see that behavior. For me, it just errors out. The difference in symptoms could be caused by 1) different hg server setups, 2) some change in our code since the issue was first reported, or 3) some other third thing.

**Comment by JaderCM** [comment]
I reported this issue with a connection with HG repository on bitbucket that is not supported any more. With this reason I will close this bug.
