### ISSUE TITLE
support for MQ

### ISSUE THREAD

**Issue by twk-b** [mrcrowl/vscode-hg#61]
Issue Type: <b>Feature Request</b>

Just basic functionality to allow QREFESH, QPOP, QPUSH, QFINISH and showing the list of patches

list of MQ patches above the current Changes on the SCM sidebar

Double click to apply to that point in the queue.

Addition button beside checkmark to refresh the patch.

Extension version: 1.2.3
VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:07:48.477Z)
OS version: Darwin x64 17.7.0

**Comment by mrcrowl** [comment]
Sorry MQ support is not on the dev radar. Feel free to submit a PR, or fork and adapt to your needs.
