### ISSUE TITLE
Error Hg: Callback must be a function on vscode insiders

### ISSUE THREAD

**Issue by onemen** [mrcrowl/vscode-hg#65]
The extension doesn't show any changes on files and any file in the source control side-bar.
Clicking on Refresh generate error notification:
> Hg: Callback must be a function

**Installation**
VS code Version: 1.31.0-insider (user setup)
Commit: 371c853fa9c6def40b6fa51071d0ba03c9f62ebb
Date: 2019-02-01T06:21:41.669Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by Amorano** [comment]
Just got this on the new update of VSCode

Version: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

**Comment by onemen** [comment]
See this PR https://github.com/KristjanTammekivi/vscode-hg/pull/1

vscode-hg is a fork of this extension

**Comment by Amorano** [comment]
> See this PR [KristjanTammekivi#1](https://github.com/KristjanTammekivi/vscode-hg/pull/1)
> 
> vscode-hg is a fork of this extension

that is fine, but i dont use that extension, regardless of it being a fork.

This should be fixed in this source base, if that requires pulling the PR from there to make it work here, someone should do that.

Meantime I simply rolled back to 1.30.2 because we have to work, not fight the tools.

**Comment by Aleksei-Badyaev** [comment]
I confirm this issue after update VS Code today.

**Comment by SVasilev** [comment]
I also confirm the issue after update VS Code today.

**Comment by gufoscuro** [comment]
same here, have the same issue after VS Code update

**Comment by kafumanto** [comment]
As the repo seems freezed since November 2017 (not a bat thing BTW as it was working :) ), @mrcrowl can we expect a fix for this issue?

**Comment by n0nag0n** [comment]
Same issue with me :(

**Comment by pitaj** [comment]
Building on what @n0nag0n said, here's how to fix the plugin with just a simple text edit:

1. Edit the file `~/.vscode/extensions/mrcrowl.hg-1.2.3/out/src/repository.js` or `C:\Users\[you]\.vscode\extensions\mrcrowl.hg-1.2.3\out\src\repository.js` on Windows
2. Find the definition of the method `unlocked()` (search for string `unlocked() {`)
3. Replace the whole method (for me it was line 835 - 843) with the following:

```js
unlocked() {
	const exists = (path) => new Promise(
		(resolve, reject) => fs.stat(path, (err) => {
				if (err) {
					if (err.code === 'ENOENT') {
						return resolve(false);
					}
					return reject(err);
				}
				resolve(true);
		})
	);
	
	return __awaiter(this, void 0, void 0, function* () {
		let attempt = 1;
		while (
			attempt <= 10 &&
			(yield exists(
				path.join(this.repository.root, '.hg', 'index.lock')
			))
		) {
			yield timeout(Math.pow(attempt, 2) * 50);
			attempt++;
		}
	});
}
```

3. Reload the VS Code window and the extension should work just fine

**Comment by zerkms** [comment]
Ohhhhh, I just realised the latest commit to the repository was in November 2017

**Comment by KristjanTammekivi** [comment]
I published new version of my fork to the marketplace with the fix for this. At work we're moving away from HG though (and same is true for mrcrowl) so I recommend someone take over the development. I don't plan on doing any development on this anymore.

**Comment by mrcrowl** [comment]
Apologies for the lack of updates here.  As mentioned above, we're moving away from mercurial at work.  I'm looking for someone interested in taking over this project.  For now v1.3.0 should address this issue.  Thanks to @KristjanTammekivi for the fix.
