### ISSUE TITLE
When multiple repos are open, commit asks me to choose which repo to commit to

### ISSUE THREAD

**Issue by feakuru** [mrcrowl/vscode-hg#67]
So I have multiple mercurial repos in my working environment, and at any moment, a repo is chosen as the current one in the SOURCE CONTROL tab. So I am able to see staged, unstaged and untracked changes for that repo and commit to it.
But when I commit, I am asked to chose which repo to commit to. If I choose a wrong one, nothing happens (I suppose commit fails silently). This choice is unnecessary. Can it be removed?

**Comment by feakuru** [comment]
Much love fir the fix, @incidentist :)

**Comment by incidentist** [comment]
All credit goes to @hdpoliveira, who is this repo's 🏆 Bugfixing Champion of the Month 🏆 , a very prestigious award I just came up with. 🙃

**Comment by hdpoliveira** [comment]
LOL
I'd like to thank all those who supported me in achieving this life-long goal of becoming the Bugfixing Champion of the Month, you are the best! :champagne:
