### ISSUE TITLE
Add ability to specify hg installation directory

### ISSUE THREAD

**Issue by EvilKot** [mrcrowl/vscode-hg#69]
In my case hg was installed via brew and located in /usr/local/bin, so extension throws the following error on startup:
```
Could not find hg, tried: 
- /Applications/TortoiseHg.app/Contents/Resources/lib/python2.7/hg
```
After patching path in hg.js file (findHgDarwin() function) i got it to work.
I'd like to be able to provide an installation directory manually.

**Comment by mrcrowl** [comment]
Interesting. Can you please submit a pull request or send me your edits to apply?

**Comment by EvilKot** [comment]
Yep, i've noticed the findHgDarwinUsingWhich method which is being called after tortoise installation lookup. 
My apologies for this messy issue and lack of investigation: while my which hg output is correct `/usr/local/bin/hg`, issue source appeared in my very specific .bash_profile config, where terminal is being cleared after every command and only last input being is shown. So screen clearing and echoing last input was separated with semicolon `;`, changing this to `&&` fixed the problem.

Thanks for your time, i believe this issue should be closed now :D
