### ISSUE TITLE
Support per-user .hgrc

### ISSUE THREAD

**Issue by jacereda** [mrcrowl/vscode-hg#7]
Looks like the extension only supports .hg/hgrc for config. I have a single .hgrc in my home path containing my settings, but if I try to commit it yields a "no username" error.

**Comment by mrcrowl** [comment]
Thanks for reporting. I'll look into this.

**Comment by mrcrowl** [comment]
@jacereda, could I get you to do a couple of things to help me problem-solve?

1. Have you configured any settings for the Hg extension?  Specifically, is `hg.commandMode` set to `"server"`?     
If your extension version is v1.0.3 or higher then the default is `"cli"`.

2. From the integrated terminal in VS Code, please run:
   ```
   hg config --debug > hgconfig.txt
   ```
   hgconfig.txt should now contain the source for each of your settings.  Please go through and XXXX out any personal details/passwords, and then email the file to mrcrowl@gmail.com.  This will help me understand where your environment is collecting settings from.

**Comment by jacereda** [comment]
Hi,

The only hg-related setting I had was:

    "hg.path": "c:/users/jacereda/apps64/Mercurial/hg.exe",


Looks like when hg can't be located in the path it won't read `~/AppData/Roaming/.hgrc` (although it reads `~/mercurial.ini` and `~/.hgrc`, so this might well be a mercurial bug. So the workaround is clear, just use `~/.hgrc` or add the mercurial executable to `%PATH%`. I moved the configuration file to the home path and `hg config --debug` shows the expected configuration.

Thanks for your help, I guess this can be closed now.
