### ISSUE TITLE
Can I exclude **/.hg/store/** from the filewatcher without breaking this add-on?

### ISSUE THREAD

**Issue by Yoric** [mrcrowl/vscode-hg#75]
Hi, I have [a PR](https://github.com/microsoft/vscode/pull/91941) to VSCode that adds `**./hg/store/**` to the filewatcher exclusion list, for performance reasons.

Will this break your add-on? If so, how can we work around that?

**Comment by hdpoliveira** [comment]
Since the PR was closed and released already, should we close this?

**Comment by Yoric** [comment]
WFM
