### ISSUE TITLE
No "Revert Change" button in inline changes window

### ISSUE THREAD

**Issue by tiktuk** [mrcrowl/vscode-hg#78]
The `Revert Change` button is missing from the inline changes window. Is that a bug or to be expected? (I'm new to VS Code.)

![Screenshot 2020-04-22 at 09 24 33](https://user-images.githubusercontent.com/153722/79952719-2122e400-847b-11ea-92fb-1fb109b098d3.png)

Here is how it looks in a git repo:

![Screenshot 2020-04-22 at 09 24 09](https://user-images.githubusercontent.com/153722/79952736-2849f200-847b-11ea-84e1-da883f3de145.png)

**Comment by incidentist** [comment]
This isn't a bug, it just hasn't been implemented yet.

**Comment by hdpoliveira** [comment]
@incidentist this is implemented now, right?

**Comment by incidentist** [comment]
Yep!
