### ISSUE TITLE
Support for "current branch" workflow

### ISSUE THREAD

**Issue by nsgundy** [mrcrowl/vscode-hg#8]
Version: 1.0.4
Thanks for the great extension, really liking it so far!

I'd like to request an option to be added that allows for the following:
* Push command will only push the current branch `hg push -r .`
* The "changes" counter (in the status bar next to the current branch name) only shows the outstanding commit to be pushed / pulled from the current branch and clicking on it will only pull / push the current branch.

The reason behind this is that I do make commits to different branches frequently, but when I decide push I only want to push the branch I am currently on. So I never just `hg push`, always `hg push -r .`.

**Comment by mrcrowl** [comment]
Sounds good.  Will look into this.

**Comment by mrcrowl** [comment]
Would you be okay if the push current branch used `hg push -b .`?  I think it's the same in most situations, but will also include other forks with the same branch name as current.

**Comment by nsgundy** [comment]
> Would you be okay if the push current branch used hg push -b .?
That would just fine 👍

**Comment by mrcrowl** [comment]
Released in v1.0.7

**Comment by nsgundy** [comment]
Thanks so much, love it!
