### ISSUE TITLE
Filename character problem

### ISSUE THREAD

**Issue by ugurozturk** [mrcrowl/vscode-hg#9]
![ch](https://cloud.githubusercontent.com/assets/7994408/26033373/8a2a04fe-38b3-11e7-9ee8-f1a4d892022c.PNG)

can't work with them. Also i am don't know if it is about to extension or hg itself

**Comment by mrcrowl** [comment]
Thanks for reporting.

Could you please paste one of the filenames into this issue so that I can do some testing?

**Comment by ugurozturk** [comment]
Kaplanoğlu
Oğuzhjan

And probabbly : ş,ö,ç,ü,ı,ğ

**Comment by ugurozturk** [comment]
![stillnotworking](https://user-images.githubusercontent.com/7994408/33048699-51c4179e-ce6d-11e7-8911-855326b6804a.JPG)

**Comment by ugurozturk** [comment]
[testmercurial.zip](https://github.com/mrcrowl/vscode-hg/files/1489595/testmercurial.zip)
