### ISSUE TITLE
Error in command Hg: Clone: Hg: There are no available repositories

### ISSUE THREAD

**Issue by hdpoliveira** [mrcrowl/vscode-hg#90]
From a new VS Code window, >Hg: Clone gives the following error:

![image](https://user-images.githubusercontent.com/35645457/85231603-04e5e980-b3cf-11ea-93ff-e7091dde640e.png)

It should be able to run fine even without open repositories

**Comment by incidentist** [comment]
Done!

**Comment by hdpoliveira** [comment]
Alright, thank you!
