### ISSUE TITLE
Create a wiki page on how to contribite

### ISSUE THREAD

**Issue by hdpoliveira** [mrcrowl/vscode-hg#94]
No need to be fancy, just something like https://github.com/JohnstonCode/svn-scm/wiki/Contributing ?

**Comment by hdpoliveira** [comment]
@mrcrowl I believe it is only you who can create a wiki page.

**Comment by mrcrowl** [comment]
@hdpoliveira I’ve now added you as a collaborator. According to [the docs](https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis), this should allow you to edit the wiki.

**Comment by hdpoliveira** [comment]
Hi @mrcrowl , it does not look to be working:
![image](https://user-images.githubusercontent.com/35645457/85905375-9eebce80-b7e1-11ea-9a51-8aee01670930.png)

According to [this link](https://help.github.com/en/github/building-a-strong-community/adding-or-editing-wiki-pages) there should be an edit button somewhere... ☹️

**Comment by mrcrowl** [comment]
Looks like your invitation to collaborate is still pending. You might need to check your inbox for a link.

**Comment by hdpoliveira** [comment]
Thanks @mrcrowl !
I created a Contributing session in the [Home wiki page](https://github.com/mrcrowl/vscode-hg/wiki).
