### ISSUE TITLE
Improve Performance of getSummary()

### ISSUE THREAD

**Issue by incidentist** [mrcrowl/vscode-hg#98]
In hg.ts, getSummary() is called frequently. It calls `hg summary`, which runs slowly on large repos. On the mozilla-central repo, `hg summary` takes 12s on my machine. `hg parents` seems to give the same information and is instantaneous on the mozilla-central repo.

Determine whether `hg parents` reliably gives us the same information as `hg summary`, and if it does, use it in getSummary(). This entails changing parseParentLines() in the same file.

If possible, write some automated tests first so we can be sure the new version works the same as the old version.

**Comment by hdpoliveira** [comment]
One thing hg parents does not do and hg summary does is check if there repository is "dirty". This is why hg summary takes so long.

I know hg id does show if the repo is dirty.

Maybe we can reduce the number of times we call hg summary by calling it only when we want to get the full picture of the repo

**Comment by hdpoliveira** [comment]
One other option is to make command server mode (https://www.mercurial-scm.org/wiki/CommandServer) the default. It seems there is an incomplete implementation in the current code, enabled by setting hg.commandMode=server.
Also there is this npm package which I'm not sure if it is still active: https://www.npmjs.com/package/hg

That is a much larger project though, but I do believe that is the way we should go for the long run.

**Comment by incidentist** [comment]
> One thing hg parents does not do and hg summary does is check if there repository is "dirty". This is why hg summary takes so long.

I always wondered about that. When we call it in getSummary(), though, we don't use any of the dirty repo stuff. Just the parent hashes and whether we're merging. There are probably a bunch of ways to optimize the "get repo status" operation, but this one seems like an easy win.

> That is a much larger project though, but I do believe that is the way we should go for the long run.

Totally. That, and using `chg` when possible. Do you know what is incomplete about the current implementation? I haven't looked at it. So many extensions and core vscode functions involves starting up a server that I'm sure there are some best practices or an API or library or something for doing it.
